version: "3.8"

services:
  overlay-frontend:
    image: yannicreust/overlay-frontend:latest
    build:
      context: .
      dockerfile: /apps/overlay-frontend/Dockerfile
    ports:
      - "5174:4173"
    networks:
      - feedflow-network

  dashboard-frontend:
    image: yannicreust/dashboard-frontend:latest
    build:
      context: .
      dockerfile: /apps/dashboard-frontend/Dockerfile
    ports:
      - "5173:80"
    restart: unless-stopped
    networks:
      - feedflow-network

  backend:
    image: yannicreust/backend:latest
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: mysql # Uses the MySQL container name
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: hmJZKzJ&&rtYwq#ppB65
      MYSQL_DATABASE: feedflow
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - feedflow-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: hmJZKzJ&&rtYwq#ppB65
      MYSQL_DATABASE: feedflow
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$$MYSQL_ROOT_PASSWORD",
        ]
      interval: 5s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - feedflow-network

volumes:
  mysql-data:

networks:
  feedflow-network:
    driver: bridge
