version: "3.8"
services:
  overlay-frontend:
    image: yannicreust/overlay-frontend:latest
    build:
      context: .
      dockerfile: /apps/overlay-frontend/Dockerfile
    ports:
      - "5174:4173"

  dashboard-frontend:
    image: yannicreust/dashboard-frontend:latest
    build:
      context: .
      dockerfile: /apps/dashboard-frontend/Dockerfile # Adjust path if your Dockerfile is somewhere else

    ports:
      - "5173:80"
    restart: unless-stopped

  backend:
    image: yannicreust/backend:latest
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile # Assuming you save the Nest Dockerfile as Dockerfile.nest
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: hmJZKzJ&&rtYwq#ppB65
      MYSQL_DATABASE: feedflow

    restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: hmJZKzJ&&rtYwq#ppB65
      MYSQL_DATABASE: feedflow
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql-data:
