# Build stage
FROM node:23-alpine AS build

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY pnpm-workspace.yaml ./
COPY package.json pnpm-lock.yaml ./

COPY apps/dashboard-frontend ./apps/dashboard-frontend
COPY packages/ui ./packages/ui
COPY packages/utils ./packages/utils
COPY packages/eslint-config ./packages/eslint-config
COPY packages/typescript-config ./packages/typescript-config

RUN pnpm install

RUN pnpm --filter ./apps/dashboard-frontend... run build

# Serve stage
FROM node:23-alpine

RUN npm install -g serve

WORKDIR /app

COPY --from=build /app/apps/dashboard-frontend/dist ./dist

EXPOSE 80

CMD ["serve", "dist","-s", "-l", "80"]
