[phases.setup]
commands = [
  "corepack enable",
  "corepack prepare pnpm@latest --activate",
  "pnpm -v"  # to check pnpm is available
]

[phases.install]
package_manager = "pnpm"
commands = [
  "pnpm install --filter=overlay-frontend..."
]

[phases.build]
commands = [
  "pnpm run build --filter=overlay-frontend..."
]