[phases.setup]
commands = [
  "corepack enable",
  "corepack prepare pnpm@latest --activate"
]

[phases.install]
package_manager = "pnpm"

[phases.build]
commands = [
  "pnpm install --filter=overlay-frontend...",
  "pnpm run build --filter=overlay-frontend..."
]